apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Optional: Common labels to be added to all resources
commonLabels:
  app: nginx

# Optional: Image update
images:
  - name: nginx
    newTag: 1.26.2

